service:
  name: viddet

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  videos:
    handler: handlers.getVideos
    events:
      - http:
          method: get
          path: v1/videos
